### ISSUE TITLE
Avatar picture in side menu not correct

### ISSUE THREAD

**Issue by AlexejHirsch** [cpunq/bugzy#1]
If i open the side menu i see not my avatar picture over my email. I see a picture of another person.

**Comment by fastestdevalive** [comment]
@AlexejHirsch Just to make sure, can you see the correct profile picture on your FogBugz dashboard?

**Comment by AlexejHirsch** [comment]
Yes. On fogbugz dashboard is the avatar picture correct.

**Comment by fastestdevalive** [comment]
Did you try to logout and login again?

**Comment by AlexejHirsch** [comment]
Just tried. Same behavior.

**Comment by AlexejHirsch** [comment]
Hi. Any update on this issue?

**Comment by AlexejHirsch** [comment]
Can that be the bug? >>> https://bluestacks.fogbugz.com <<<

https://github.com/cpunq/bugzy/blob/2477101af04e59c804b78760c7a9964659a28c73/app/src/main/java/in/bugzy/ui/home/PeopleFragment.java#L218

There are mode code lines in your app which includes url "https://bluestacks.fogbugz.com"

**Comment by gbhola-bst** [comment]
Yes @AlexejHirsch you are right.
I just figured that out some days back but couldn't work on it. How about you fixing this and submitting a pull request? We will be more than happy to accept :).
Thanks a lot for your efforts.

**Comment by AlexejHirsch** [comment]
Sorry, i have no time for this :)

**Comment by fastestdevalive** [comment]
@AlexejHirsch Can you try the latest version?
